In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['台北','台中', '台南', '高雄'],
                   columns=['one', 'two', 'three', 'four'])
df

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [2]:
#drop  用來刪除特定index的資料
df.drop(index=['台北', '高雄'], inplace=True)
df

    one  two  three  four
台中    4    5      6     7
台南    8    9     10    11

In [4]:
#排序和排名

scores = np.random.randint(50,101,size=(50, 5))
df = pd.DataFrame(scores,
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=['學生' + str(i) for i in range(1, 51)])
df.index.name = '學生'
df.columns.name = '科目'
sum_values = df.sum(axis=1)
mean_values = df.mean(axis=1)
df['總分'] = sum_values
df['平均'] = mean_values
df

科目     國文   英文   數學  自然   社會   總分    平均
學生
學生1    75   82   94  74   57  382  76.4
學生2    81   82   80  75  100  418  83.6
學生3    79   74   81  52   96  382  76.4
學生4    81   79   90  97  100  447  89.4
學生5    75   81   77  91   89  413  82.6
學生6    79   80   92  78   55  384  76.8
學生7    53   58   69  59   58  297  59.4
學生8    89   89   88  61   92  419  83.8
學生9    93   83  100  87   53  416  83.2
學生10   70   74   62  80   60  346  69.2
學生11   98   89   96  92   76  451  90.2
學生12   64   89   79  72   57  361  72.2
學生13   73   59   76  51   92  351  70.2
學生14   77   98   57  76   51  359  71.8
學生15   69   91   60  94   75  389  77.8
學生16   84   64   95  62   63  368  73.6
學生17   71   50   84  63   87  355  71.0
學生18   75   78   74  80   90  397  79.4
學生19   81   59   88  84   52  364  72.8
學生20   81   78   75  80   83  397  79.4
學生21   91   96   81  53   99  420  84.0
學生22   86   82   95  78   63  404  80.8
學生23   85   73   83  80   79  400  80.0
學生24   73   74   97  68   77  389  77.8
學生25   60   56   95  62   61  334  66.8
學生26   90   77   60  58   78  363  72.6
學生27   79   91   80  74   89  413  82.6
學生28   58  100   94  77   80  409  81.8
學生29   91   95   78  78   77  419  83.8
學生30   51   55   77  67   60  310  62.0
學生31   98   64   86  89   54  391  78.2
學生32   81   82   77  82   61  383  76.6
學生33   65   68   54  58   88  333  66.6
學生34   85   82   97  64   95  423  84.6
學生35   63   67   70  76   91  367  73.4
學生36   64   54   66  98   89  371  74.2
學生37   95   92   60  73   91  411  82.2
學生38   82   70   57  89   74  372  74.4
學生39   74   66   84  89   77  390  78.0
學生40   50   92   62  68   87  359  71.8
學生41   94   82   98  87   69  430  86.0
學生42   70   56   78  87   83  374  74.8
學生43   81   68   82  59   71  361  72.2
學生44  100  100   77  63   65  405  81.0
學生45   61  100   65  77   68  371  74.2
學生46   54   98   73  92   84  401  80.2
學生47   77   52   73  77   55  334  66.8
學生48   79   84   74  80   65  382  76.4
學生49   88   79   57  77   84  385  77.0
學生50   57   82   87  77   64  367  73.4

In [14]:
#排序和排名
#rank()
rank_values = sum_values.rank(method='min', ascending=False)
df['排名'] = rank_values
df

科目     國文  英文   數學   自然   社會   總分    平均    名次    排名
學生
學生1    54  82   50   64   72  322  64.4  48.0  48.0
學生2    91  64   64   58   90  367  73.4  34.0  34.0
學生3    96  51   79   75   93  394  78.8  14.0  14.0
學生4    65  71   87   61   92  376  75.2  26.0  26.0
學生5    54  51   83   55   81  324  64.8  47.0  47.0
學生6    98  87   59  100   52  396  79.2  12.0  12.0
學生7    65  70   91   62   72  360  72.0  36.0  36.0
學生8    86  84   65   59   52  346  69.2  42.0  42.0
學生9    65  83   61   58   66  333  66.6  46.0  46.0
學生10   59  64   51   92   88  354  70.8  37.0  37.0
學生11   69  55   65   63   70  322  64.4  48.0  48.0
學生12   61  65   57   66   61  310  62.0  50.0  50.0
學生13   61  79   80   61   67  348  69.6  40.0  40.0
學生14   55  63   78   72  100  368  73.6  32.0  32.0
學生15   76  95   51   75   79  376  75.2  26.0  26.0
學生16   66  55   96   66   84  367  73.4  34.0  34.0
學生17   77  91   98   79   68  413  82.6   5.0   5.0
學生18   96  98   98   78  100  470  94.0   1.0   1.0
學生19   99  85   51   72   61  368  73.6  32.0  32.0
學生20   59  90   93   81   84  407  81.4   6.0   6.0
學生21   64  90   83   69   80  386  77.2  19.0  19.0
學生22   96  68   93   52   96  405  81.0   7.0   7.0
學生23   75  67   79   84   76  381  76.2  24.0  24.0
學生24   55  95   73   97   64  384  76.8  22.0  22.0
學生25   83  96   98   60   98  435  87.0   3.0   3.0
學生26   63  97   77   57   58  352  70.4  38.0  38.0
學生27   82  75   79   70   87  393  78.6  17.0  17.0
學生28  100  60   75   50   91  376  75.2  26.0  26.0
學生29   78  72   88   97   65  400  80.0  10.0  10.0
學生30   77  61   80   79   97  394  78.8  14.0  14.0
學生31   57  96   59   88   95  395  79.0  13.0  13.0
學生32   51  77   96   74   72  370  74.0  31.0  31.0
學生33   86  72   98   51   70  377  75.4  25.0  25.0
學生34   52  83   85   96   84  400  80.0  10.0  10.0
學生35   95  62   76   55  100  388  77.6  18.0  18.0
學生36   58  64   97   67   50  336  67.2  45.0  45.0
學生37   93  92   79   84   57  405  81.0   7.0   7.0
學生38   52  82   51   81   81  347  69.4  41.0  41.0
學生39   93  96   78   64   52  383  76.6  23.0  23.0
學生40   55  81   68   97   70  371  74.2  30.0  30.0
學生41   77  82   96   96   68  419  83.8   4.0   4.0
學生42   98  86   67   93   60  404  80.8   9.0   9.0
學生43   83  92   57   62   52  346  69.2  42.0  42.0
學生44  100  57   92   91   54  394  78.8  14.0  14.0
學生45   92  55   72   62   93  374  74.8  29.0  29.0
學生46   62  72  100   57   58  349  69.8  39.0  39.0
學生47   78  59   87  100   62  386  77.2  19.0  19.0
學生48   69  54   77   53   89  342  68.4  44.0  44.0
學生49   89  88   88   87   98  450  90.0   2.0   2.0
學生50   56  62   87   95   86  386  77.2  19.0  19.0

In [15]:
#sort_values()
#sort_index()
df1 = df.sort_values(by='總分', ascending=False)
df1

科目     國文  英文   數學   自然   社會   總分    平均    名次    排名
學生
學生18   96  98   98   78  100  470  94.0   1.0   1.0
學生49   89  88   88   87   98  450  90.0   2.0   2.0
學生25   83  96   98   60   98  435  87.0   3.0   3.0
學生41   77  82   96   96   68  419  83.8   4.0   4.0
學生17   77  91   98   79   68  413  82.6   5.0   5.0
學生20   59  90   93   81   84  407  81.4   6.0   6.0
學生37   93  92   79   84   57  405  81.0   7.0   7.0
學生22   96  68   93   52   96  405  81.0   7.0   7.0
學生42   98  86   67   93   60  404  80.8   9.0   9.0
學生29   78  72   88   97   65  400  80.0  10.0  10.0
學生34   52  83   85   96   84  400  80.0  10.0  10.0
學生6    98  87   59  100   52  396  79.2  12.0  12.0
學生31   57  96   59   88   95  395  79.0  13.0  13.0
學生3    96  51   79   75   93  394  78.8  14.0  14.0
學生44  100  57   92   91   54  394  78.8  14.0  14.0
學生30   77  61   80   79   97  394  78.8  14.0  14.0
學生27   82  75   79   70   87  393  78.6  17.0  17.0
學生35   95  62   76   55  100  388  77.6  18.0  18.0
學生47   78  59   87  100   62  386  77.2  19.0  19.0
學生50   56  62   87   95   86  386  77.2  19.0  19.0
學生21   64  90   83   69   80  386  77.2  19.0  19.0
學生24   55  95   73   97   64  384  76.8  22.0  22.0
學生39   93  96   78   64   52  383  76.6  23.0  23.0
學生23   75  67   79   84   76  381  76.2  24.0  24.0
學生33   86  72   98   51   70  377  75.4  25.0  25.0
學生28  100  60   75   50   91  376  75.2  26.0  26.0
學生15   76  95   51   75   79  376  75.2  26.0  26.0
學生4    65  71   87   61   92  376  75.2  26.0  26.0
學生45   92  55   72   62   93  374  74.8  29.0  29.0
學生40   55  81   68   97   70  371  74.2  30.0  30.0
學生32   51  77   96   74   72  370  74.0  31.0  31.0
學生19   99  85   51   72   61  368  73.6  32.0  32.0
學生14   55  63   78   72  100  368  73.6  32.0  32.0
學生2    91  64   64   58   90  367  73.4  34.0  34.0
學生16   66  55   96   66   84  367  73.4  34.0  34.0
學生7    65  70   91   62   72  360  72.0  36.0  36.0
學生10   59  64   51   92   88  354  70.8  37.0  37.0
學生26   63  97   77   57   58  352  70.4  38.0  38.0
學生46   62  72  100   57   58  349  69.8  39.0  39.0
學生13   61  79   80   61   67  348  69.6  40.0  40.0
學生38   52  82   51   81   81  347  69.4  41.0  41.0
學生8    86  84   65   59   52  346  69.2  42.0  42.0
學生43   83  92   57   62   52  346  69.2  42.0  42.0
學生48   69  54   77   53   89  342  68.4  44.0  44.0
學生36   58  64   97   67   50  336  67.2  45.0  45.0
學生9    65  83   61   58   66  333  66.6  46.0  46.0
學生5    54  51   83   55   81  324  64.8  47.0  47.0
學生1    54  82   50   64   72  322  64.4  48.0  48.0
學生11   69  55   65   63   70  322  64.4  48.0  48.0
學生12   61  65   57   66   61  310  62.0  50.0  50.0

In [9]:
#排序和排名
#用Copilot改的#用Copilot改的#用Copilot改的#用Copilot改的

scores = np.random.randint(50,101,size=(50, 5))
df = pd.DataFrame(scores,
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=['學生' + str(i) for i in range(1, 51)])
df.index.name = '學生'
df.columns.name = '科目'
sum_values = df.sum(axis=1)
mean_values = df.mean(axis=1)
df['總分'] = sum_values
df['平均'] = mean_values
#依據總分的高低分名次,總分最高的學生為第一名
df['名次'] = df['總分'].rank(ascending=False, method='min')
df

科目     國文  英文   數學   自然   社會   總分    平均    名次
學生
學生1    54  82   50   64   72  322  64.4  48.0
學生2    91  64   64   58   90  367  73.4  34.0
學生3    96  51   79   75   93  394  78.8  14.0
學生4    65  71   87   61   92  376  75.2  26.0
學生5    54  51   83   55   81  324  64.8  47.0
學生6    98  87   59  100   52  396  79.2  12.0
學生7    65  70   91   62   72  360  72.0  36.0
學生8    86  84   65   59   52  346  69.2  42.0
學生9    65  83   61   58   66  333  66.6  46.0
學生10   59  64   51   92   88  354  70.8  37.0
學生11   69  55   65   63   70  322  64.4  48.0
學生12   61  65   57   66   61  310  62.0  50.0
學生13   61  79   80   61   67  348  69.6  40.0
學生14   55  63   78   72  100  368  73.6  32.0
學生15   76  95   51   75   79  376  75.2  26.0
學生16   66  55   96   66   84  367  73.4  34.0
學生17   77  91   98   79   68  413  82.6   5.0
學生18   96  98   98   78  100  470  94.0   1.0
學生19   99  85   51   72   61  368  73.6  32.0
學生20   59  90   93   81   84  407  81.4   6.0
學生21   64  90   83   69   80  386  77.2  19.0
學生22   96  68   93   52   96  405  81.0   7.0
學生23   75  67   79   84   76  381  76.2  24.0
學生24   55  95   73   97   64  384  76.8  22.0
學生25   83  96   98   60   98  435  87.0   3.0
學生26   63  97   77   57   58  352  70.4  38.0
學生27   82  75   79   70   87  393  78.6  17.0
學生28  100  60   75   50   91  376  75.2  26.0
學生29   78  72   88   97   65  400  80.0  10.0
學生30   77  61   80   79   97  394  78.8  14.0
學生31   57  96   59   88   95  395  79.0  13.0
學生32   51  77   96   74   72  370  74.0  31.0
學生33   86  72   98   51   70  377  75.4  25.0
學生34   52  83   85   96   84  400  80.0  10.0
學生35   95  62   76   55  100  388  77.6  18.0
學生36   58  64   97   67   50  336  67.2  45.0
學生37   93  92   79   84   57  405  81.0   7.0
學生38   52  82   51   81   81  347  69.4  41.0
學生39   93  96   78   64   52  383  76.6  23.0
學生40   55  81   68   97   70  371  74.2  30.0
學生41   77  82   96   96   68  419  83.8   4.0
學生42   98  86   67   93   60  404  80.8   9.0
學生43   83  92   57   62   52  346  69.2  42.0
學生44  100  57   92   91   54  394  78.8  14.0
學生45   92  55   72   62   93  374  74.8  29.0
學生46   62  72  100   57   58  349  69.8  39.0
學生47   78  59   87  100   62  386  77.2  19.0
學生48   69  54   77   53   89  342  68.4  44.0
學生49   89  88   88   87   98  450  90.0   2.0
學生50   56  62   87   95   86  386  77.2  19.0