In [16]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame


def create_student_dataframe():
    scores = np.random.randint(50, 101, size=(50, 5))
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

In [18]:
scores = np.random.randint(50,101,size=(50, 5))
df = create_student_dataframe()
df

#AI建立一個function
#依據df
#建立1個統計的DataFrame
#欄位: ['國文', '英文', '數學', '自然', '社會']
#欄位: ['平均', '最高', '最低', '中間值']

def create_statistics_dataframe(df):
    stats = pd.DataFrame(index=['平均', '最高', '最低', '中間值'])
    stats['國文'] = [df['國文'].mean(), df['國文'].max(), df['國文'].min(), df['國文'].median()]
    stats['英文'] = [df['英文'].mean(), df['英文'].max(), df['英文'].min(), df['英文'].median()]
    stats['數學'] = [df['數學'].mean(), df['數學'].max(), df['數學'].min(), df['數學'].median()]
    stats['自然'] = [df['自然'].mean(), df['自然'].max(), df['自然'].min(), df['自然'].median()]
    stats['社會'] = [df['社會'].mean(), df['社會'].max(), df['社會'].min(), df['社會'].median()]
    return stats
df

科目    國文   英文  數學  自然   社會   總分    平均    排名
學生
學生1   75   84  51  97   91  398  79.6  13.0
學生2   81   94  76  66   76  393  78.6  18.0
學生3   80   62  67  85   73  367  73.4  32.0
學生4   50   84  50  53   99  336  67.2  47.0
學生5   69   63  86  51   81  350  70.0  42.0
學生6   88   92  67  94   87  428  85.6   2.0
學生7   95   88  88  66   59  396  79.2  15.0
學生8   73   65  67  57   81  343  68.6  45.0
學生9   96   51  50  78   71  346  69.2  44.0
學生10  55   93  92  66   73  379  75.8  26.0
學生11  74   76  93  92   83  418  83.6   5.0
學生12  66   89  97  70   51  373  74.6  31.0
學生13  95   98  54  84   53  384  76.8  25.0
學生14  65   91  50  58   94  358  71.6  34.0
學生15  53   73  97  92   86  401  80.2   8.0
學生16  95   75  84  68   77  399  79.8  10.0
學生17  90   99  86  87   79  441  88.2   1.0
學生18  56  100  83  89  100  428  85.6   2.0
學生19  98   52  83  83   50  366  73.2  33.0
學生20  58   77  77  86   78  376  75.2  29.0
學生21  83   72  72  89   75  391  78.2  20.0
學生22  84   68  55  90   98  395  79.0  16.0
學生23  91   93  66  75   64  389  77.8  23.0
學生24  89   74  86  54   97  400  80.0   9.0
學生25  94   81  50  69   60  354  70.8  38.0
學生26  85   55  61  73   80  354  70.8  38.0
學生27  71   65  59  63   97  355  71.0  37.0
學生28  96   75  79  96   67  413  82.6   6.0
學生29  69   68  74  59   56  326  65.2  48.0
學生30  63   71  83  66   65  348  69.6  43.0
學生31  55   70  90  55   50  320  64.0  49.0
學生32  62   88  76  55   57  338  67.6  46.0
學生33  67   79  85  55   92  378  75.6  27.0
學生34  73   83  64  52   84  356  71.2  36.0
學生35  88   95  54  93   69  399  79.8  10.0
學生36  89   80  58  82   80  389  77.8  23.0
學生37  87   82  78  50  100  397  79.4  14.0
學生38  70   93  85  53   73  374  74.8  30.0
學生39  91   71  74  63   59  358  71.6  34.0
學生40  70  100  53  66   88  377  75.4  28.0
學生41  84   83  55  69  100  391  78.2  20.0
學生42  80   86  99  77   61  403  80.6   7.0
學生43  86   52  71  82  100  391  78.2  20.0
學生44  93   56  95  98   57  399  79.8  10.0
學生45  71   79  93  72   79  394  78.8  17.0
學生46  76   79  83  98   86  422  84.4   4.0
學生47  53   66  54  85   57  315  63.0  50.0
學生48  56   57  65  90   85  353  70.6  40.0
學生49  51   91  69  67   73  351  70.2  41.0
學生50  89   93  85  51   74  392  78.4  19.0

In [19]:
#建立1個統計的DataFrame
stats_df = create_statistics_dataframe(df)
stats_df

        國文      英文     數學     自然     社會
平均   76.56   78.22  73.38  73.38   76.5
最高   98.00  100.00  99.00  98.00  100.0
最低   50.00   51.00  50.00  50.00   50.0
中間值  78.00   79.00  75.00  71.00   77.5